# Database
spring:
    datasource:
        url: jdbc:mysql://dueline.c38apc6xiqdx.ap-south-1.rds.amazonaws.com/fineline?createDatabaseIfNotExist=true
        username: admin
        password: ${AWS_MYSQL_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
# Hazelcast
hazelcast:
    enabled: false
# AWS related
cloud:
    aws:
        region:
            static: ap-south-1
        queue:
            name: student-add
            end-point: https://sqs.ap-south-1.amazonaws.com/559129048391/student-add
        sns:
            topic:
                arn: arn:aws:sqs:ap-south-1:559129048391:student-add
server:
    port: 8000
