# Database
spring:
    datasource:
        url: jdbc:mysql://dueline.c38apc6xiqdx.ap-south-1.rds.amazonaws.com/fineline?createDatabaseIfNotExist=true
#        url: jdbc:mysql://fineline-database-service:3310/fineline?createDatabaseIfNotExist=true
        username: admin
        password: sreerAM31&
    jpa:
        hibernate:
            ddl-auto: update
# Hazelcast
hazelcast:
    enabled: false
# AWS related
cloud:
    aws:
        region:
            static: ap-south-1
        credentials:
            access-key: AKIAYELVQGVD4Y5NEOHF
            secret-key: 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
        queue:
            name: student-add
            end-point: https://sqs.ap-south-1.amazonaws.com/559129048391/student-add
        sns:
            topic:
                arn: arn:aws:sqs:ap-south-1:559129048391:student-add
server:
    port: 8080


# AWS MYSQL RDS
#spring.datasource.url=jdbc:mysql://varane.cqwyqvafdom2.ap-south-1.rds.amazonaws.com:3307/varane
#spring.datasource.username=admin
#spring.datasource.password=i_remembered_to_delete_my_password

# H2 (in-memory)
#spring.h2.console.enabled=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:myDb
#spring.jpa.hibernate.ddl-auto=update